#backend-deployment.yaml

apiVersion: apps/v1

kind: Deployment

metadata:

  name: backend-dpl

spec:

  replicas: 1

  selector:

    matchLabels:

      app: backend

  template:

    metadata:

      labels:

        app: backend

    spec:

      containers:

name: backend-container

          image: lmnzr/simplebackend:latest

          resources:

            limits:

              memory: "128Mi"

              cpu: "500m"

          ports:

name: go-backend

              containerPort: 8080
