apiVersion: v1

kind: Service

metadata:

  name: rpc-app-service

  labels:

    app: rpc-app

    release: prometheus

spec:

  ports:

name: web

    port: 8081

    targetPort: 8081

    protocol: TCP

  selector:

    app: rpc-app

---

apiVersion: monitoring.coreos.com/v1

kind: ServiceMonitor

metadata:

  name: rpc-app

  labels:

    env: production

    release: prometheus

spec:

  selector:

    matchLabels:

      app: rpc-app

  endpoints:

port: web


